parameters:
#    msi_cms.example.class: Msi\CmsBundle\Example

services:
    msi_cms.page_listener:
        class: Msi\CmsBundle\EventListener\PageListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_cms.block_listener:
        class: Msi\CmsBundle\EventListener\BlockListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_cms.menu_listener:
        class: Msi\CmsBundle\EventListener\MenuListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_cms.twig.extension.cms:
        class: Msi\CmsBundle\Twig\Extension\CmsExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    # msi_cms.mailer:
    #     class: Msi\CmsBundle\Mailer\Mailer
    #     arguments: [@mailer, @msi_cms.email_manager, @templating]




# admins

    msi_cms_page_admin:
        class: %msi_cms.page.admin%
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
