Msi\CmsBundle\Entity\Page:
    properties:
        template:
            - NotBlank: ~

Msi\CmsBundle\Entity\PageTranslation:
    properties:
        title:
            - NotBlank: ~

Msi\CmsBundle\Entity\Block:
    properties:
        name:
            - NotBlank: ~

Msi\CmsBundle\Entity\Email:
    properties:
        name:
            - NotBlank: ~
        fromWho:
            - NotBlank: ~
            - Email: ~

Msi\CmsBundle\Entity\EmailTranslation:
    properties:
        subject:
            - NotBlank: ~
        body:
            - NotBlank: ~
